-- SUPERSEDED — do not run this file.
--
-- This file was never added to supabase/migrations/, so it was never
-- reliably applied. It also used `create table if not exists`, which
-- silently no-ops against the `subscriptions` table that already existed
-- from 20260709174725_create_subscriptions_table.sql — so even attempts
-- to run it directly would not have added the Paddle-specific columns.
--
-- The real fix lives in a tracked, idempotent migration:
--   supabase/migrations/20260721120000_reconcile_paddle_subscriptions_schema.sql
--
-- Apply that migration (via the Supabase CLI / MCP against the project
-- referenced in supabase/config.toml) instead of this file.
